sensors:
  #- sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    #point_cloud_topic: /camera/depth_registered/points
     #max_range: 5.0
     #padding_offset: 0
     #padding_scale: 1
     #point_subsample: 1
     ##NOTE: filtered_cloud_topic apparently causes a slowdown, use rtealtime_urdf_filter instead
     ##filtered_cloud_topic: output_cloud
  #- sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
     #image_topic: /camera/depth_registered/image_raw
     #queue_size: 1
     #near_clipping_plane_distance: 0.3
     #far_clipping_plane_distance: 10.0
     #skip_vertical_pixels: 1
     #skip_horizontal_pixels: 1
     #shadow_threshold: 0.2
     #padding_scale: 4.0
     #padding_offset: 0.0
     #filtered_cloud_topic: output_cloud
  - sensor_plugin: occupancy_map_monitor/RealtimeURDFFilterOctomapUpdater
    fixed_frame: /world
    camera_frame: /camera_rgb_optical_frame # this is epcified in the launchfile
    # OLD: image_topic: /camera/depth_registered/image_raw
    depth_input_image_topic: /camera/depth_registered/image_raw
    depth_input_camera_info_topic: /camera/depth_registered/camera_info
    depth_filtered_topic: /camera/depth_registered_filtered2/hw_registered/image_rect_raw
    depth_mask_topic: /camera/depth_mask
    camera_offset:
      translation:   [0.0,0.0,0.0] #[0.00,0.0,-0.06]
      rotation:    [0.0,0.0,0.0,1.0]
    # There is one entry for each URDIF that should be filtered
    models:
      - { model: "/robot_description", tf_prefix: "" }
      - { model: "/stage_model", tf_prefix: "" } # TODO: move this into lcsr-specific launchfile
    #- model: "/arm_1/robot_description"
    #  tf_prefix: "/arm_0"
    #- model: "table_description"
    #  tf_prefix: ""
    # how far in front of the robot model is still deleted? (e.g. 0.05 = 5cm)
    depth_distance_threshold: -0.02
    show_gui: true
    filter_replace_value: 0.0
    # collision or visual
    geometry_type: collision
    # inflation distance [m]
    inflation: 0.010


